import "./globals.css";
import Header from "../components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header /> 
        <main className="container mx-auto p-4 sm:p-6 lg:p-8">
            {children} 
        </main>
      </body>
    </html>
  );
}
